clone:
  git:
    image: plugins/git
    # path: github.com/mephux/uchit
    branch: master
    depth: 32767

workspace:
  base: /go
  path: src/github.com/mephux/uchit

pipeline:
  normal:
    image: mephux/docker-golang
    environment:
      - GO15VENDOREXPERIMENT=1
    commands:
      - make
    when:
      event: [push]
  dist:
    image: mephux/docker-golang
    environment:
      - GO15VENDOREXPERIMENT=1
    commands:
      - apk add --update rpm ruby-dev gcc make > /dev/null 2>&1
      - gem install fpm --no-rdoc --no-ri
      - make dist
    when:
      event: [tag]
publish:
  github_release:
    api_key: $$GITHUB
    files: dist/*xz
    file_exists: fail
    # draft: true
    when:
      event: tag
