[Komanda]
  Debug = false
  LogFile = "/home/dweb/.komanda/komanda.log"

[Server]
  Host = "irc.freenode.net"
  Port = "6667"
  SSL = false
  Insecure = true
  Nick = "Komanda"
  User = "Komanda"
  Password = ""
  auto_connect = false

[Color]
  Black = 0
  White = 15
  Red = 160
  Purple = 92
  Logo = 75
  Yellow = 11
  Green = 119
  Menu = 209
  my_nick = 164
  other_nick_default = 14
  Timestamp = 247
  my_text = 129
  Header = 57
  QueryHeader = 11
  current_input_view = 215

[Time]
  message_format = "15:04"
  notice_format = "02 Jan 06 15:04 MST"
  menu_format = "03:04:05 PM"
